/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkeasy;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static parkeasy.RecoveryPassward.connection;

/**
 *
 * @author Atiq
 */
public class AddUser extends javax.swing.JPanel {

    /**
     * Creates new form AboutUs
     */
    int user_id, search_id;
    String name, username, phone, email, address, securityQuestion, answer, customerType, paymentType, password, confirmPassword;

    private static Connection connection = null;
    private byte[] image = null;

    public AddUser() {
        initComponents();
        connection = DbConnect.dbconnect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTA = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JPanel();
        fontCancel = new javax.swing.JLabel();
        btnSave = new javax.swing.JPanel();
        fontSave = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JPanel();
        fontEdit = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        usernameTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        answerTF = new javax.swing.JTextField();
        securityquestionComboBox = new javax.swing.JComboBox<>();
        passwordTF = new javax.swing.JPasswordField();
        confirmpasswordTF = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        customertypeComboBox = new javax.swing.JComboBox<>();
        paymenttypeCombobox = new javax.swing.JComboBox<>();
        passwardMatchLabel = new javax.swing.JLabel();
        showMessageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        photoLabel = new javax.swing.JLabel();
        chosePhotoButton = new javax.swing.JPanel();
        fontChosePhoto = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        searchTF = new javax.swing.JTextField();
        clearButton1 = new javax.swing.JLabel();
        searchButton1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pathShowLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(710, 470));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 470));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 62, 80));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 62, 80));
        jLabel3.setText("Phone:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 62, 80));
        jLabel4.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 62, 80));
        jLabel7.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 62, 80));
        jLabel6.setText("Passward:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 62, 80));
        jLabel5.setText("Confirm Passward:");

        nameTF.setBackground(new java.awt.Color(109, 122, 138));
        nameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameTF.setForeground(new java.awt.Color(255, 255, 255));

        phoneTF.setBackground(new java.awt.Color(109, 122, 138));
        phoneTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneTF.setForeground(new java.awt.Color(255, 255, 255));

        emailTF.setBackground(new java.awt.Color(109, 122, 138));
        emailTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailTF.setForeground(new java.awt.Color(255, 255, 255));

        addressTA.setBackground(new java.awt.Color(109, 122, 138));
        addressTA.setColumns(20);
        addressTA.setForeground(new java.awt.Color(255, 255, 255));
        addressTA.setLineWrap(true);
        addressTA.setRows(5);
        jScrollPane1.setViewportView(addressTA);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("Add new User");

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setPreferredSize(new java.awt.Dimension(150, 24));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });

        fontCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Erase_20px.png"))); // NOI18N
        fontCancel.setText("Clear");
        fontCancel.setIconTextGap(8);

        javax.swing.GroupLayout btnCancelLayout = new javax.swing.GroupLayout(btnCancel);
        btnCancel.setLayout(btnCancelLayout);
        btnCancelLayout.setHorizontalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCancelLayout.setVerticalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnCancelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fontCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setPreferredSize(new java.awt.Dimension(150, 24));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });

        fontSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Save_20px.png"))); // NOI18N
        fontSave.setText("Save");
        fontSave.setIconTextGap(8);

        javax.swing.GroupLayout btnSaveLayout = new javax.swing.GroupLayout(btnSave);
        btnSave.setLayout(btnSaveLayout);
        btnSaveLayout.setHorizontalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontSave, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnSaveLayout.setVerticalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnSaveLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(fontSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUpdate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdate.setPreferredSize(new java.awt.Dimension(150, 41));
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdateMouseExited(evt);
            }
        });

        fontEdit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Edit_Property_20px.png"))); // NOI18N
        fontEdit.setText("Update");
        fontEdit.setIconTextGap(8);

        javax.swing.GroupLayout btnUpdateLayout = new javax.swing.GroupLayout(btnUpdate);
        btnUpdate.setLayout(btnUpdateLayout);
        btnUpdateLayout.setHorizontalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnUpdateLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnUpdateLayout.setVerticalGroup(
            btnUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontEdit, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 62, 80));
        jLabel9.setText("User Name:");

        usernameTF.setBackground(new java.awt.Color(109, 122, 138));
        usernameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        usernameTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 62, 80));
        jLabel10.setText("Security Question:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(45, 62, 80));
        jLabel12.setText("Answer:");

        answerTF.setBackground(new java.awt.Color(109, 122, 138));
        answerTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        answerTF.setForeground(new java.awt.Color(255, 255, 255));

        securityquestionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "What is yolur favorite car?", "What is your favorite car color?" }));

        passwordTF.setBackground(new java.awt.Color(109, 122, 138));
        passwordTF.setForeground(new java.awt.Color(255, 255, 255));

        confirmpasswordTF.setBackground(new java.awt.Color(109, 122, 138));
        confirmpasswordTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 62, 80));
        jLabel13.setText("Customer Type:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(45, 62, 80));
        jLabel14.setText("Payment Type:");

        customertypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Regular", "Premium" }));

        paymenttypeCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Cash", "Others", " " }));
        paymenttypeCombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymenttypeComboboxActionPerformed(evt);
            }
        });

        passwardMatchLabel.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        passwardMatchLabel.setForeground(new java.awt.Color(204, 0, 0));

        showMessageLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        showMessageLabel.setForeground(new java.awt.Color(204, 0, 0));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 2, true));

        photoLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        chosePhotoButton.setBackground(new java.awt.Color(255, 255, 255));
        chosePhotoButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        chosePhotoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chosePhotoButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                chosePhotoButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                chosePhotoButtonMouseExited(evt);
            }
        });

        fontChosePhoto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontChosePhoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Google_Images_30px_1.png"))); // NOI18N
        fontChosePhoto.setText("Chose Photo");
        fontChosePhoto.setIconTextGap(8);

        javax.swing.GroupLayout chosePhotoButtonLayout = new javax.swing.GroupLayout(chosePhotoButton);
        chosePhotoButton.setLayout(chosePhotoButtonLayout);
        chosePhotoButtonLayout.setHorizontalGroup(
            chosePhotoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chosePhotoButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontChosePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
        );
        chosePhotoButtonLayout.setVerticalGroup(
            chosePhotoButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontChosePhoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chosePhotoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chosePhotoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        searchTF.setToolTipText("Search by User Name ");
        searchTF.setBorder(null);

        clearButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Delete_20px_1.png"))); // NOI18N
        clearButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButton1MouseClicked(evt);
            }
        });

        searchButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Search_20px_1.png"))); // NOI18N
        searchButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchButton1)
                .addGap(10, 10, 10)
                .addComponent(searchTF, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton1)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clearButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(searchTF, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(searchButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Enter user name to update information");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel12))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(securityquestionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                                .addComponent(phoneTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(usernameTF, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailTF, javax.swing.GroupLayout.Alignment.LEADING))
                                            .addComponent(answerTF, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(customertypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(paymenttypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(confirmpasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(pathShowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(showMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(passwardMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(passwardMatchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(showMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(securityquestionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(answerTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel13)
                                    .addComponent(customertypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel14)
                                    .addComponent(paymenttypeCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(confirmpasswordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pathShowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here    
        setclickedcolor(btnCancel, fontCancel);

        nameTF.setText("");
        usernameTF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        addressTA.setText("");
        securityquestionComboBox.setSelectedItem("Select one");
        answerTF.setText("");
        customertypeComboBox.setSelectedItem("Select one");
        paymenttypeCombobox.setSelectedItem("Select one");
        passwordTF.setText("");
        confirmpasswordTF.setText("");
        showMessageLabel.setText("");
        pathShowLabel.setText("");
        photoLabel.setText("");
        //byte[] imageData = null;
        ImageIcon formate;
        formate = new ImageIcon("man.png");
        photoLabel.setIcon(formate);


    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        // TODO add your handling code here:
        setselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:

        getdata();
        if (name.isEmpty() || username.isEmpty() || phone.isEmpty() || email.isEmpty() || address.isEmpty() || securityQuestion.equals("Select one")
                || answer.isEmpty() || customerType.equals("Select one") || paymentType.equals("Select one") || password.isEmpty() || confirmPassword.isEmpty()) {
            showMessageLabel.setText("Some fields are required!");
        } else if (!password.equals(confirmPassword)) {
            showMessageLabel.setText("");
            showMessageLabel.setText("Password does not matched!");
            passwordTF.requestFocus();

        } else {

            try {

                String sql = "select * from users where user_name='" + username + "'";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();

                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "user name is exist!");
                    //userNameTF.requestFocus();
                    st.close();
                    rs.close();
                    usernameTF.requestFocus();
                } else {
                    try {

                        String sql_1 = "insert into users"
                                + "(user_name,user_type,password,security_question,answer,photo)"
                                + " values(?,?,?,?,?,?)";
                        PreparedStatement statement2 = connection.prepareStatement(sql_1);
                        statement2.setString(1, username);
                        statement2.setString(2, "customer");
                        statement2.setString(3, password);
                        statement2.setString(4, securityQuestion);
                        statement2.setString(5, answer);
                        statement2.setBytes(6, image);

                        statement2.executeUpdate();
                        statement2.close();
                        showMessageLabel.setText("");

                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                    try {
                        String sql_2 = "select * from users where user_name='" + username + "'";
                        PreparedStatement st1 = connection.prepareStatement(sql_2);
                        ResultSet rs1 = st1.executeQuery();

                        if (rs1.next()) {

                            user_id = rs1.getInt("id");
                            st1.close();
                            rs1.close();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                    try {
                        String sql_1 = "insert into customer"
                                + "(user_id,name,phone,email,address,type,payment)"
                                + " values(?,?,?,?,?,?,?)";

                        PreparedStatement statement = connection.prepareStatement(sql_1);

                        statement.setInt(1, user_id);
                        statement.setString(2, name);
                        statement.setString(3, phone);
                        statement.setString(4, email);
                        statement.setString(5, address);
                        statement.setString(6, customerType);
                        statement.setString(7, paymentType);

                        statement.executeUpdate();

                        System.out.println("Insrt sucessfull");
                        JOptionPane.showMessageDialog(null, "Registration sucessfull");

                        showMessageLabel.setText("");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }
                }

            } catch (Exception e) {
            }

        }

        image = null;

        setclickedcolor(btnSave, fontSave);
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered

        // TODO add your handling code here:
        setselectcolor(btnSave, fontSave);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnSave, fontSave);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        setclickedcolor(btnUpdate, fontEdit);

        getdata();

        if (name.isEmpty() || username.isEmpty() || phone.isEmpty() || email.isEmpty()
                || address.isEmpty() || securityQuestion.equals("Select one")
                || answer.isEmpty() || customerType.equals("Select one")
                || paymentType.equals("Select one") || password.isEmpty() || confirmPassword.isEmpty()) {
            showMessageLabel.setText("Some fields are required!");
        } else if (!password.equals(confirmPassword)) {
            showMessageLabel.setText("");
            showMessageLabel.setText("Password does not matched!");
            passwordTF.requestFocus();

        } else {
            try {

                String sql = "select * from users where id='" + search_id + "'";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();

                if (rs.next()) {

                    if (!rs.getString("password").equals(passwordTF.getText())) {
                        JOptionPane.showMessageDialog(null, "You have to enter your correct password !");
                        st.close();
                        rs.close();
                    } else {

                        try {

                            String sql2 = "update users set user_name = '" + usernameTF.getText()
                                    + "',security_question='" + securityquestionComboBox.getSelectedItem()
                                    + "',answer='" + answerTF.getText()
                                    + "' where id='" + search_id + "'";
                            PreparedStatement statement = connection.prepareStatement(sql2);
                            statement.executeUpdate();
                            statement.close();
                            //

                            showMessageLabel.setText("");
                        } catch (Exception e) {
                        }

                        try {

                            String sql3 = "update customer set name = '" + nameTF.getText()
                                    + "',phone='" + phoneTF.getText()
                                    + "',email='" + emailTF.getText()
                                    + "',address='" + addressTA.getText()
                                    + "',type='" + customertypeComboBox.getSelectedItem()
                                    + "',payment='" + paymenttypeCombobox.getSelectedItem() + "' where user_id='" + search_id + "'";
                            PreparedStatement statement2 = connection.prepareStatement(sql3);
                            statement2.executeUpdate();
                            JOptionPane.showMessageDialog(null, "Update is successful.");
                            statement2.close();

                            showMessageLabel.setText("");
                        } catch (Exception e) {
                        }
                        if (image != null) {
                            try {

                                String sql2 = "update users set photo=? where id='" + search_id + "'";
                                PreparedStatement statement = connection.prepareStatement(sql2);
                                statement.setBytes(1, image);
                                statement.executeUpdate();
                                statement.close();
                                //JOptionPane.showMessageDialog(null, "Photo is updated.");

                            } catch (Exception ex) {
                                JOptionPane.showMessageDialog(this, ex);
                            }
                            image = null;
                            pathShowLabel.setText("");
                        }

                    }
                }

            } catch (Exception e) {
            }

        }


    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        // TODO add your handling code here:
        setselectcolor(btnUpdate, fontEdit);
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnUpdate, fontEdit);
    }//GEN-LAST:event_btnUpdateMouseExited

    private void chosePhotoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chosePhotoButtonMouseClicked
        // TODO add your handling code here:

        // ImageIcon imageIcon= new ImageIcon(); 
        setclickedcolor(chosePhotoButton, fontChosePhoto);

        JFileChooser filechooser = new JFileChooser();
        filechooser.showOpenDialog(null);
        File file = filechooser.getSelectedFile();
        String path = file.getAbsolutePath();
        pathShowLabel.setText(path);

        try {
            FileInputStream fIS = new FileInputStream(file);
            ByteArrayOutputStream bAOS = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];
            for (int readNum; (readNum = fIS.read(buf)) != -1;) {
                bAOS.write(buf, 0, readNum);
            }
            image = bAOS.toByteArray();
        } catch (Exception e) {
        }

    }//GEN-LAST:event_chosePhotoButtonMouseClicked

    private void chosePhotoButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chosePhotoButtonMouseEntered
        // TODO add your handling code here:
        setselectcolor(chosePhotoButton, fontChosePhoto);
    }//GEN-LAST:event_chosePhotoButtonMouseEntered

    private void chosePhotoButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chosePhotoButtonMouseExited
        // TODO add your handling code here:
        resetselectcolor(chosePhotoButton, fontChosePhoto);
    }//GEN-LAST:event_chosePhotoButtonMouseExited

    private void clearButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButton1MouseClicked
        // TODO add your handling code here:
        searchTF.setText("");
    }//GEN-LAST:event_clearButton1MouseClicked

    private void searchButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButton1MouseClicked
        // TODO add your handling code here:

        String searchkey;
        searchkey = searchTF.getText();

        try {
            String sql = "select * from users where user_name='" + searchkey + "'";
            PreparedStatement st = connection.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            if (rs.next()) {

                if (rs.getString("user_type").equals("park_owner")) {
                    JOptionPane.showMessageDialog(null, "You have no permission to edit this account !");
                } else {

                    usernameTF.setText(rs.getString("user_name"));
                    securityquestionComboBox.setSelectedItem(rs.getString("security_question"));
                    //answerTF.setText(rs.getString("answer"));
                    search_id = rs.getInt("id");
                    byte[] imageData = rs.getBytes("photo");
                    if(imageData!=null){
                        ImageIcon formate = new ImageIcon(imageData);
                    photoLabel.setIcon(formate);
                    }
                    

                    try {
                        String sql2 = "select * from customer where user_id='" + search_id + "'";
                        PreparedStatement st2 = connection.prepareStatement(sql2);
                        ResultSet rs2 = st2.executeQuery();

                        if (rs2.next()) {

                            nameTF.setText(rs2.getString("name"));
                            phoneTF.setText(rs2.getString("phone"));
                            emailTF.setText(rs2.getString("email"));
                            addressTA.setText(rs2.getString("address"));
                            customertypeComboBox.setSelectedItem(rs2.getString("type"));
                            paymenttypeCombobox.setSelectedItem(rs2.getString("payment"));
                            st.close();
                            rs.close();
                        }
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(this, ex);
                        
                    }

                    st.close();
                    rs.close();
                }

            } else {
                JOptionPane.showMessageDialog(null, "user name is not exist!");
                st.close();
                rs.close();
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_searchButton1MouseClicked

    private void paymenttypeComboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymenttypeComboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymenttypeComboboxActionPerformed

    void setselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(255, 250, 250));
        label.setForeground(new Color(31, 58, 147));
    }

    void setclickedcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(31, 58, 147));
        label.setForeground(Color.white);
    }

    void resetselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(Color.WHITE);
        label.setForeground(Color.BLACK);
    }

    void getdata() {
        name = nameTF.getText();
        username = usernameTF.getText();
        phone = phoneTF.getText();
        email = emailTF.getText();
        address = addressTA.getText();
        securityQuestion = (String) securityquestionComboBox.getSelectedItem();
        answer = answerTF.getText();
        customerType = (String) customertypeComboBox.getSelectedItem();
        paymentType = (String) paymenttypeCombobox.getSelectedItem();
        password = passwordTF.getText();
        confirmPassword = confirmpasswordTF.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTA;
    private javax.swing.JTextField answerTF;
    private javax.swing.JPanel btnCancel;
    private javax.swing.JPanel btnSave;
    private javax.swing.JPanel btnUpdate;
    private javax.swing.JPanel chosePhotoButton;
    private javax.swing.JLabel clearButton1;
    private javax.swing.JPasswordField confirmpasswordTF;
    private javax.swing.JComboBox<String> customertypeComboBox;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel fontCancel;
    private javax.swing.JLabel fontChosePhoto;
    private javax.swing.JLabel fontEdit;
    private javax.swing.JLabel fontSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel passwardMatchLabel;
    private javax.swing.JPasswordField passwordTF;
    private javax.swing.JLabel pathShowLabel;
    private javax.swing.JComboBox<String> paymenttypeCombobox;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel searchButton1;
    private javax.swing.JTextField searchTF;
    private javax.swing.JComboBox<String> securityquestionComboBox;
    private javax.swing.JLabel showMessageLabel;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
