/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkeasy;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Atiq
 */
public class NewEntry extends javax.swing.JPanel {

    /**
     * Creates new form NewEntry
     */
    private static Connection connection = null;
    String s, parkedTableName, userName, sensorTableName;
    int search_id, rate, oldp[], status = 0;

    SimpleDateFormat dateformater, timeformater;
    Date date;
    private int u_id;
    private String u_name;
    private String positiontf;
    Home home;
    private String p;

    public NewEntry() {
        initComponents();

    }

    public NewEntry(int id, String user_name) {
        this.u_id = id;
        this.u_name = user_name;
        initComponents();

        parkedTableName = u_name + "_parked_status";
        sensorTableName = u_name + "_sensor_status";
        oldp = new int[14];
        connection = DbConnect.dbconnect();
        setfeeAndPosition();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        phoneTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTA = new javax.swing.JTextArea();
        vehicalNoTf = new javax.swing.JTextField();
        positionTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        feeTF = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JPanel();
        fontCancel = new javax.swing.JLabel();
        btnSave = new javax.swing.JPanel();
        fontSave = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        entryTimeTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        paymentTypeTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        searchTF = new javax.swing.JTextField();
        clearButton = new javax.swing.JLabel();
        searchButton = new javax.swing.JLabel();
        showMessageLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        paymentstatusCombo = new javax.swing.JComboBox<>();
        vehicalTypeCombo = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(700, 478));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 470));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(45, 62, 80));
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 62, 80));
        jLabel3.setText("Phone:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 62, 80));
        jLabel4.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 62, 80));
        jLabel7.setText("Address:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 62, 80));
        jLabel6.setText("Vehical type:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 62, 80));
        jLabel5.setText("Vehical No:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 62, 80));
        jLabel11.setText("Position:");

        nameTF.setBackground(new java.awt.Color(109, 122, 138));
        nameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameTF.setForeground(new java.awt.Color(255, 255, 255));

        phoneTF.setBackground(new java.awt.Color(109, 122, 138));
        phoneTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneTF.setForeground(new java.awt.Color(255, 255, 255));

        addressTA.setBackground(new java.awt.Color(109, 122, 138));
        addressTA.setColumns(20);
        addressTA.setForeground(new java.awt.Color(255, 255, 255));
        addressTA.setLineWrap(true);
        addressTA.setRows(5);
        jScrollPane1.setViewportView(addressTA);

        vehicalNoTf.setBackground(new java.awt.Color(109, 122, 138));
        vehicalNoTf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vehicalNoTf.setForeground(new java.awt.Color(255, 255, 255));

        positionTF.setBackground(new java.awt.Color(109, 122, 138));
        positionTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        positionTF.setForeground(new java.awt.Color(255, 255, 255));
        positionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionTFActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(45, 62, 80));
        jLabel1.setText("Fee (Tk):");

        feeTF.setBackground(new java.awt.Color(109, 122, 138));
        feeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        feeTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 0));
        jLabel8.setText("New Parking Entry Form");

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setPreferredSize(new java.awt.Dimension(150, 24));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });

        fontCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fontCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Erase_20px.png"))); // NOI18N
        fontCancel.setText("Clear");
        fontCancel.setIconTextGap(8);

        javax.swing.GroupLayout btnCancelLayout = new javax.swing.GroupLayout(btnCancel);
        btnCancel.setLayout(btnCancelLayout);
        btnCancelLayout.setHorizontalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCancelLayout.setVerticalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setPreferredSize(new java.awt.Dimension(150, 24));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });

        fontSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontSave.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fontSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Save_20px.png"))); // NOI18N
        fontSave.setText("confirm Entry");
        fontSave.setIconTextGap(8);

        javax.swing.GroupLayout btnSaveLayout = new javax.swing.GroupLayout(btnSave);
        btnSave.setLayout(btnSaveLayout);
        btnSaveLayout.setHorizontalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontSave, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnSaveLayout.setVerticalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontSave, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 62, 80));
        jLabel9.setText("User Name:");

        userNameTF.setBackground(new java.awt.Color(109, 122, 138));
        userNameTF.setForeground(new java.awt.Color(255, 255, 255));
        userNameTF.setToolTipText("optional");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(45, 62, 80));
        jLabel12.setText("Entry Time:");

        entryTimeTF.setBackground(new java.awt.Color(109, 122, 138));
        entryTimeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        entryTimeTF.setForeground(new java.awt.Color(255, 255, 255));
        entryTimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTimeTFActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 62, 80));
        jLabel10.setText("Payment Type: ");

        paymentTypeTF.setBackground(new java.awt.Color(109, 122, 138));
        paymentTypeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentTypeTF.setForeground(new java.awt.Color(255, 255, 255));

        emailTF.setBackground(new java.awt.Color(109, 122, 138));
        emailTF.setForeground(new java.awt.Color(255, 255, 255));
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        searchTF.setToolTipText("Search by User Name ");
        searchTF.setBorder(null);

        clearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Delete_20px_1.png"))); // NOI18N
        clearButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        searchButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Search_20px_1.png"))); // NOI18N
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchButton)
                .addGap(10, 10, 10)
                .addComponent(searchTF, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearButton)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(clearButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
            .addComponent(searchTF, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        showMessageLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        showMessageLabel.setForeground(new java.awt.Color(204, 0, 0));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 62, 80));
        jLabel13.setText("Payment status: ");

        paymentstatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Paid", "Due" }));

        vehicalTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Car", "Motor bike" }));

        jLabel14.setForeground(new java.awt.Color(0, 102, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Exm:LA-32-586");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(showMessageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(positionTF, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(entryTimeTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(phoneTF)
                                .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(vehicalTypeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(paymentstatusCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGap(96, 96, 96)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(paymentTypeTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(feeTF, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(emailTF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(vehicalNoTf, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel9)
                            .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(vehicalNoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(vehicalTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(feeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(paymentTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(paymentstatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel7))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entryTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void positionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionTFActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        setclickedcolor(btnCancel, fontCancel);

        nameTF.setText("");
        userNameTF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        addressTA.setText("");
        vehicalNoTf.setText("");
        vehicalTypeCombo.setSelectedIndex(0);
        positionTF.setText("");
        feeTF.setText("");
        paymentTypeTF.setText("");
        showMessageLabel.setText("");
        entryTimeTF.setText("");
        paymentstatusCombo.setSelectedIndex(0);
        searchTF.setText("");

    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        // TODO add your handling code here:
        setselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:

        ArrayList<String> list = new ArrayList();
        ArrayList<String> list2 = new ArrayList();
        ArrayList<Integer> list3 = new ArrayList();
        int i;
        setclickedcolor(btnSave, fontSave);
        dateformater = new SimpleDateFormat("dd/MM/yyyy");
        timeformater = new SimpleDateFormat("HH:mm");
        date = new Date();
        String time = timeformater.format(date);
        entryTimeTF.setText(time);

        if (userNameTF.getText().isEmpty()) {
            userNameTF.setText("Not Registered");
        }

        try {

            String sql_1 = "select * from " + parkedTableName + " ";
            PreparedStatement st = connection.prepareStatement(sql_1);
            ResultSet rs = st.executeQuery();
            while (rs.next()) {
                list3.add(rs.getInt("status"));
            }
            st.close();
            rs.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        for (i = 0; i < list3.size(); i++) {
            if (list3.get(i) == 1) {
                status = 1;
            }
        }

        //end     
        if (status == 1) {
            if (nameTF.getText().isEmpty() || phoneTF.getText().isEmpty()
                    || paymentstatusCombo.getSelectedItem().equals("Select one")
                    || emailTF.getText().isEmpty() || addressTA.getText().isEmpty()
                    || vehicalNoTf.getText().isEmpty() || vehicalTypeCombo.getSelectedItem().equals("Select one")
                    || positionTF.getText().isEmpty() || feeTF.getText().isEmpty()
                    || entryTimeTF.getText().isEmpty() || paymentTypeTF.getText().isEmpty()) {
                showMessageLabel.setText("Some fields are required!");
            } else {

                try {

                    String sql_2 = "select * from " + parkedTableName + " where status='" + 1 + "' ";
                    PreparedStatement st1 = connection.prepareStatement(sql_2);
                    ResultSet rs_1 = st1.executeQuery();

                    while (rs_1.next()) {
                        list.add(rs_1.getString("vehical_no"));
                        list2.add(rs_1.getString("position"));
                    }

                    st1.close();
                    rs_1.close();

                } catch (Exception e) {
                    e.printStackTrace();
                }

                for (i = 0; i < list.size(); i++) {
                    if (list.get(i).equals(vehicalNoTf.getText())) {
                        s = "y";
                    } else {
                        s = "n";
                    }
                }

                for (i = 0; i < list2.size(); i++) {
                    if (list2.get(i).equals(positionTF.getText())) {
                        p = "y";
                    } else {
                        p = "n";
                    }
                }

                if (!s.equals("y") && !p.equals("y")) {

                    Home home = new Home(u_id, u_name);
                    home.Home(parkedTableName, nameTF.getText(), userNameTF.getText(), phoneTF.getText(), emailTF.getText(),
                            addressTA.getText(), vehicalNoTf.getText(), vehicalTypeCombo.getSelectedItem().toString(), feeTF.getText(), paymentTypeTF.getText(),
                            positionTF.getText(), paymentstatusCombo.getSelectedItem().toString(), 1);
                    
                     nameTF.setText("");
        userNameTF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        addressTA.setText("");
        vehicalNoTf.setText("");
        vehicalTypeCombo.setSelectedIndex(0);
        positionTF.setText("");
        feeTF.setText("");
        paymentTypeTF.setText("");
        showMessageLabel.setText("");
        entryTimeTF.setText("");
        paymentstatusCombo.setSelectedIndex(0);
        searchTF.setText("");


                } else if (s.equals("y")) {
                    JOptionPane.showMessageDialog(null, "Car is already parked.");
                    showMessageLabel.setText("");
                } else if (p.equals("y")) {
                    JOptionPane.showMessageDialog(null, "Position is already bocked.");
                    showMessageLabel.setText("");
                }

                status=0;
            }
        } 
        else {
            Home home = new Home(u_id, u_name);
            home.Home(parkedTableName, nameTF.getText(), userNameTF.getText(), phoneTF.getText(), emailTF.getText(),
                    addressTA.getText(), vehicalNoTf.getText(), vehicalTypeCombo.getSelectedItem().toString(), feeTF.getText(), paymentTypeTF.getText(),
                    positionTF.getText(), paymentstatusCombo.getSelectedItem().toString(), 1);
            
                                
                     nameTF.setText("");
        userNameTF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        addressTA.setText("");
        vehicalNoTf.setText("");
        vehicalTypeCombo.setSelectedIndex(0);
        positionTF.setText("");
        feeTF.setText("");
        paymentTypeTF.setText("");
        showMessageLabel.setText("");
        entryTimeTF.setText("");
        paymentstatusCombo.setSelectedIndex(0);
        searchTF.setText("");
        }


    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered

        // TODO add your handling code here:
        setselectcolor(btnSave, fontSave);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnSave, fontSave);
    }//GEN-LAST:event_btnSaveMouseExited

    private void entryTimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTimeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryTimeTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
        // TODO add your handling code here:

        searchTF.setText("");

    }//GEN-LAST:event_clearButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        // TODO add your handling code here:
        dateformater = new SimpleDateFormat("dd/MM/yyyy");
        timeformater = new SimpleDateFormat("HH:mm");
        date = new Date();
        String time = timeformater.format(date);
        String new_date = dateformater.format(date);
        String searchkey;
        searchkey = searchTF.getText();

        try {
            String sql = "select * from users where user_name='" + searchkey + "'";
            PreparedStatement st = connection.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            if (rs.next()) {

                if (rs.getString("user_type").equals("park_owner")) {
                    JOptionPane.showMessageDialog(null, "You are not a customer!");
                } else {

                    search_id = rs.getInt("id");

                    try {
                        String sql2 = "select * from customer where user_id='" + search_id + "'";
                        PreparedStatement st2 = connection.prepareStatement(sql2);
                        ResultSet rs2 = st2.executeQuery();

                        if (rs2.next()) {

                            nameTF.setText(rs2.getString("name"));
                            phoneTF.setText(rs2.getString("phone"));
                            emailTF.setText(rs2.getString("email"));
                            addressTA.setText(rs2.getString("address"));
                            entryTimeTF.setText(time);
                            userNameTF.setText(searchkey);
                            paymentTypeTF.setText(rs2.getString("payment"));
                            st.close();
                            rs.close();
                        }
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                    try {

                        String sql_1 = "select * from " + sensorTableName + " where date='" + new_date + "'";
                        PreparedStatement st1 = connection.prepareStatement(sql_1);
                        ResultSet rs_1 = st1.executeQuery();

                        if (rs_1.next()) {

                            oldp[0] = rs_1.getInt("p1");
                            oldp[1] = rs_1.getInt("p2");
                            oldp[2] = rs_1.getInt("p3");
                            oldp[3] = rs_1.getInt("p4");
                            oldp[4] = rs_1.getInt("p5");
                            oldp[5] = rs_1.getInt("p6");
                            oldp[6] = rs_1.getInt("p7");
                            oldp[7] = rs_1.getInt("p8");
                            oldp[8] = rs_1.getInt("p9");
                            oldp[9] = rs_1.getInt("p10");
                            oldp[10] = rs_1.getInt("p11");
                            oldp[11] = rs_1.getInt("p12");
                            oldp[12] = rs_1.getInt("p13");
                            oldp[13] = rs_1.getInt("p14");

                        }
                    } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e);

                    }

                    if (oldp[0] == 0) {
                        positiontf = "Block-A Park-1";
                    } else if (oldp[1] == 0) {
                        positiontf = "Block-A Park-2";
                    } else if (oldp[2] == 0) {
                        positiontf = "Block-A Park-3";
                    } else if (oldp[3] == 0) {
                        positiontf = "Block-A Park-4";
                    } else if (oldp[4] == 0) {
                        positiontf = "Block-B Park-1";
                    } else if (oldp[5] == 0) {
                        positiontf = "Block-B Park-2";
                    } else if (oldp[6] == 0) {
                        positiontf = "Block-B Park-3";
                    } else if (oldp[7] == 0) {
                        positiontf = "Block-B Park-4";
                    } else if (oldp[8] == 0) {
                        positiontf = "Block-C Park-1";
                    } else if (oldp[9] == 0) {
                        positiontf = "Block-C Park-2";
                    } else if (oldp[10] == 0) {
                        positiontf = "Block-C Park-3";
                    } else if (oldp[11] == 0) {
                        positiontf = "Block-C Park-4";
                    } else if (oldp[12] == 0) {
                        positiontf = "Block-D Park-1";
                    } else if (oldp[13] == 0) {
                        positiontf = "Block-D Park-2";
                    } else {
                        positiontf = "No park is available";
                    }

                    positionTF.setText(positiontf);

                    feeTF.setText((String.valueOf(rate)));
                    //positionTF.setText(positiontf);
                    st.close();
                    rs.close();
                }

            } else {
                JOptionPane.showMessageDialog(null, "user name is not exist!");
                st.close();
                rs.close();
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_searchButtonMouseClicked

    void setselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(255, 250, 250));
        label.setForeground(new Color(31, 58, 147));
    }

    void setclickedcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(31, 58, 147));
        label.setForeground(Color.white);
    }

    void resetselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(Color.WHITE);
        label.setForeground(Color.BLACK);
    }

    public void setfeeAndPosition() {

        dateformater = new SimpleDateFormat("dd/MM/yyyy");
        timeformater = new SimpleDateFormat("HH:mm");
        date = new Date();
        String time = timeformater.format(date);
        String new_date = dateformater.format(date);
        entryTimeTF.setText(time);

        try {
            String sql = "select * from park_owner where user_id='" + u_id + "'";
            PreparedStatement st = connection.prepareStatement(sql);
            ResultSet rs = st.executeQuery();

            if (rs.next()) {

                rate = rs.getInt("rate");
                st.close();
                rs.close();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        feeTF.setText(String.valueOf(rate));

        try {

            String sql_1 = "select * from " + sensorTableName + " where date='" + new_date + "'";
            PreparedStatement st1 = connection.prepareStatement(sql_1);
            ResultSet rs_1 = st1.executeQuery();

            if (rs_1.next()) {

                oldp[0] = rs_1.getInt("p1");
                oldp[1] = rs_1.getInt("p2");
                oldp[2] = rs_1.getInt("p3");
                oldp[3] = rs_1.getInt("p4");
                oldp[4] = rs_1.getInt("p5");
                oldp[5] = rs_1.getInt("p6");
                oldp[6] = rs_1.getInt("p7");
                oldp[7] = rs_1.getInt("p8");
                oldp[8] = rs_1.getInt("p9");
                oldp[9] = rs_1.getInt("p10");
                oldp[10] = rs_1.getInt("p11");
                oldp[11] = rs_1.getInt("p12");
                oldp[12] = rs_1.getInt("p13");
                oldp[13] = rs_1.getInt("p14");

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e);

        }

        if (oldp[0] == 0) {
            positiontf = "Block-A Park-1";
        } else if (oldp[1] == 0) {
            positiontf = "Block-A Park-2";
        } else if (oldp[2] == 0) {
            positiontf = "Block-A Park-3";
        } else if (oldp[3] == 0) {
            positiontf = "Block-A Park-4";
        } else if (oldp[4] == 0) {
            positiontf = "Block-B Park-1";
        } else if (oldp[5] == 0) {
            positiontf = "Block-B Park-2";
        } else if (oldp[6] == 0) {
            positiontf = "Block-B Park-3";
        } else if (oldp[7] == 0) {
            positiontf = "Block-B Park-4";
        } else if (oldp[8] == 0) {
            positiontf = "Block-C Park-1";
        } else if (oldp[9] == 0) {
            positiontf = "Block-C Park-2";
        } else if (oldp[10] == 0) {
            positiontf = "Block-C Park-3";
        } else if (oldp[11] == 0) {
            positiontf = "Block-C Park-4";
        } else if (oldp[12] == 0) {
            positiontf = "Block-D Park-1";
        } else if (oldp[13] == 0) {
            positiontf = "Block-D Park-2";
        } else {
            positiontf = "No park is available";
        }

        positionTF.setText(positiontf);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTA;
    private javax.swing.JPanel btnCancel;
    private javax.swing.JPanel btnSave;
    private javax.swing.JLabel clearButton;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField entryTimeTF;
    private javax.swing.JTextField feeTF;
    private javax.swing.JLabel fontCancel;
    private javax.swing.JLabel fontSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameTF;
    private javax.swing.JTextField paymentTypeTF;
    private javax.swing.JComboBox<String> paymentstatusCombo;
    private javax.swing.JTextField phoneTF;
    private javax.swing.JTextField positionTF;
    private javax.swing.JLabel searchButton;
    private javax.swing.JTextField searchTF;
    private javax.swing.JLabel showMessageLabel;
    private javax.swing.JTextField userNameTF;
    private javax.swing.JTextField vehicalNoTf;
    private javax.swing.JComboBox<String> vehicalTypeCombo;
    // End of variables declaration//GEN-END:variables
}
