/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkeasy;

import java.awt.Color;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Atiq
 */
public class NewEntryFromBooking extends javax.swing.JFrame {

    /**
     * Creates new form ReleseForm
     */
    ArrayList<String> list = new ArrayList();
    Home home;
    int u_id, fee, extra, due, paid, topay;
    String u_name;
    String dateAvail = "n";
    private static Connection connection = null;
    String parkedTableName;
    int cashReceive = 0;

    //Home home;
    public NewEntryFromBooking() {
        initComponents();
        this.setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("parking.png")));
        //  home=new Home(u_id,u_name);
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        connection = DbConnect.dbconnect();
        //home=new Home(u_id, u_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        userNameTF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTA = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        positionTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        entryTimeTF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        vehicalNoTf = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        vehicalTypeCombo = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        feeTF = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        paymentTypeTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        paymentstatusCombo = new javax.swing.JComboBox<>();
        btnCancel = new javax.swing.JPanel();
        fontCancel = new javax.swing.JLabel();
        showMessageLabel = new javax.swing.JLabel();
        saveBtn = new javax.swing.JPanel();
        saveFont = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 148, 6));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Demo Station");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true), "New Entry Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Vijaya", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ParkEasy");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/parking (10).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 62, 80));
        jLabel3.setText("Name:");

        nameTF.setBackground(new java.awt.Color(109, 122, 138));
        nameTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nameTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(45, 62, 80));
        jLabel9.setText("User Name:");

        userNameTF.setBackground(new java.awt.Color(109, 122, 138));
        userNameTF.setForeground(new java.awt.Color(255, 255, 255));
        userNameTF.setToolTipText("optional");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 62, 80));
        jLabel4.setText("Phone:");

        phoneTF.setBackground(new java.awt.Color(109, 122, 138));
        phoneTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        phoneTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(45, 62, 80));
        jLabel7.setText("Address:");

        addressTA.setBackground(new java.awt.Color(109, 122, 138));
        addressTA.setColumns(20);
        addressTA.setForeground(new java.awt.Color(255, 255, 255));
        addressTA.setLineWrap(true);
        addressTA.setRows(5);
        jScrollPane1.setViewportView(addressTA);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(45, 62, 80));
        jLabel11.setText("Position:");

        positionTF.setBackground(new java.awt.Color(109, 122, 138));
        positionTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        positionTF.setForeground(new java.awt.Color(255, 255, 255));
        positionTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionTFActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(45, 62, 80));
        jLabel12.setText("Entry Time:");

        entryTimeTF.setBackground(new java.awt.Color(109, 122, 138));
        entryTimeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        entryTimeTF.setForeground(new java.awt.Color(255, 255, 255));
        entryTimeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryTimeTFActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(45, 62, 80));
        jLabel5.setText("Email:");

        emailTF.setBackground(new java.awt.Color(109, 122, 138));
        emailTF.setForeground(new java.awt.Color(255, 255, 255));
        emailTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTFActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 62, 80));
        jLabel6.setText("Vehical No:");

        vehicalNoTf.setBackground(new java.awt.Color(109, 122, 138));
        vehicalNoTf.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vehicalNoTf.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(45, 62, 80));
        jLabel8.setText("Vehical type:");

        vehicalTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Car", "Motor bike" }));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 62, 80));
        jLabel10.setText("Fee (Tk):");

        feeTF.setBackground(new java.awt.Color(109, 122, 138));
        feeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        feeTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(45, 62, 80));
        jLabel29.setText("Payment Type: ");

        paymentTypeTF.setBackground(new java.awt.Color(109, 122, 138));
        paymentTypeTF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        paymentTypeTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 62, 80));
        jLabel13.setText("Payment status: ");

        paymentstatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select one", "Paid", "Due" }));

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setPreferredSize(new java.awt.Dimension(150, 24));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });

        fontCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontCancel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fontCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Redo_20px.png"))); // NOI18N
        fontCancel.setText("Cancel");
        fontCancel.setIconTextGap(8);

        javax.swing.GroupLayout btnCancelLayout = new javax.swing.GroupLayout(btnCancel);
        btnCancel.setLayout(btnCancelLayout);
        btnCancelLayout.setHorizontalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCancelLayout.setVerticalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        showMessageLabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        showMessageLabel.setForeground(new java.awt.Color(204, 0, 0));

        saveBtn.setBackground(new java.awt.Color(255, 255, 255));
        saveBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.setPreferredSize(new java.awt.Dimension(150, 41));
        saveBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saveBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saveBtnMouseExited(evt);
            }
        });

        saveFont.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveFont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Save_20px.png"))); // NOI18N
        saveFont.setText("Confirm");
        saveFont.setIconTextGap(8);

        javax.swing.GroupLayout saveBtnLayout = new javax.swing.GroupLayout(saveBtn);
        saveBtn.setLayout(saveBtnLayout);
        saveBtnLayout.setHorizontalGroup(
            saveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveBtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveFont, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        saveBtnLayout.setVerticalGroup(
            saveBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(saveFont, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(showMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel29)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(feeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entryTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicalTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vehicalNoTf, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(paymentstatusCombo, javax.swing.GroupLayout.Alignment.LEADING, 0, 240, Short.MAX_VALUE)
                                .addComponent(paymentTypeTF, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(showMessageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel9)
                    .addComponent(userNameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel6)
                    .addComponent(vehicalNoTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(vehicalTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel11)
                    .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel12)
                    .addComponent(entryTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(feeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(paymentTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel13)
                    .addComponent(paymentstatusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanel3.setBackground(new java.awt.Color(249, 148, 6));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void positionTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionTFActionPerformed

    private void entryTimeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryTimeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryTimeTFActionPerformed

    private void emailTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTFActionPerformed

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        setclickedcolor(btnCancel, fontCancel);

        nameTF.setText("");
        userNameTF.setText("");
        phoneTF.setText("");
        emailTF.setText("");
        addressTA.setText("");
        vehicalNoTf.setText("");
        vehicalTypeCombo.setSelectedIndex(0);
        positionTF.setText("");
        feeTF.setText("");
        paymentTypeTF.setText("");
        showMessageLabel.setText("");
        entryTimeTF.setText("");
        paymentstatusCombo.setSelectedIndex(0);
        this.dispose();
        // searchTF.setText("");
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        // TODO add your handling code here:
        setselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    private void saveBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseClicked
        // TODO add your handling code here:
        setclickedcolor(saveBtn, saveFont);
        String position = "";

        if (nameTF.getText().isEmpty() || phoneTF.getText().isEmpty()
                || paymentstatusCombo.getSelectedItem().equals("Select one")
                || emailTF.getText().isEmpty() || addressTA.getText().isEmpty()
                || vehicalNoTf.getText().isEmpty() || vehicalTypeCombo.getSelectedItem().equals("Select one")
                || positionTF.getText().isEmpty() || feeTF.getText().isEmpty()
                || entryTimeTF.getText().isEmpty() || paymentTypeTF.getText().isEmpty()) {
            showMessageLabel.setText("Some fields are required!");
        } else {

            int paid = 0, due = 0;
            if (paymentstatusCombo.getSelectedItem().toString().equals("Paid")) {
                paid = Integer.parseInt(feeTF.getText());
                due = 0;
            } else {
                paid = 0;
                due = Integer.parseInt(feeTF.getText());
            }

            if (!positionTF.getText().equals("No park is available")) {
                SimpleDateFormat dateformater = new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat timeformater = new SimpleDateFormat("HH:mm:ss");
                Date date = new Date();

                try {
                    String sql_1 = "insert into " + parkedTableName + ""
                            + "(name,user_name,phone,email,address,vehical_type,vehical_no,"
                            + "position,fee,paid,due,payment,payment_status,"
                            + "date,time,entry_time,status)"
                            + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
                    PreparedStatement statement2 = connection.prepareStatement(sql_1);

                    statement2.setString(1, nameTF.getText());
                    statement2.setString(2, userNameTF.getText());
                    statement2.setString(3, phoneTF.getText());
                    statement2.setString(4, emailTF.getText());
                    statement2.setString(5, addressTA.getText());
                    statement2.setString(6, vehicalTypeCombo.getSelectedItem().toString());
                    statement2.setString(7, vehicalNoTf.getText());
                    statement2.setString(8, positionTF.getText());
                    statement2.setString(9, feeTF.getText());
                    statement2.setInt(10, paid);
                    statement2.setInt(11, due);
                    statement2.setString(12, paymentTypeTF.getText());
                    statement2.setString(13, paymentstatusCombo.getSelectedItem().toString());
                    statement2.setString(14, dateformater.format(date));
                    statement2.setString(15, timeformater.format(date));
                    statement2.setString(16, timeformater.format(date) + " " + dateformater.format(date));
                    statement2.setInt(17, 1);

                    statement2.executeUpdate();
                    statement2.close();
                    JOptionPane.showMessageDialog(null, "New entry successful");
                    //showMessageLabel.setText("");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }

                //test
               switch (positionTF.getText()) {
                    case "Block-A Park-1":
                        position = "p1";
                        break;
                    case "Block-A Park-2":
                        position = "p2";
                        break;
                    case "Block-A Park-3":
                        position = "p3";
                        break;
                    case "Block-A Park-4":
                        position = "p4";
                        break;
                    case "Block-B Park-1":
                        position = "p5";
                        break;
                    case "Block-B Park-2":
                        position = "p6";
                        break;
                    case "Block-B Park-3":
                        position = "p7";
                        break;
                    case "Block-B Park-4":
                        position = "p8";
                        break;
                    case "Block-C Park-1":
                        position = "p9";
                        break;
                    case "Block-C Park-2":
                        position = "p10";
                        break;
                    case "Block-C Park-3":
                        position = "p11";
                        break;
                    case "Block-C Park-4":
                        position = "p12";
                        break;
                    case "Block-D Park-1":
                        position = "p13";
                        break;
                    case "Block-D Park-2":
                        position = "p14";
                        break;                 
                }
               try {
                                String sql = "update book_notification set approval_status ='confirm',position='"+position+"' "
                                        + " where vehicle_no='" +vehicalNoTf.getText() + "' AND status='1'AND park_name"
                                        + "='"+titleLabel.getText()+"'";
                                PreparedStatement statement = connection.prepareStatement(sql);
                                statement.executeUpdate();

                                statement.close();
                            } catch (Exception e) {
                                e.printStackTrace();
                            }

                //endtest
                if (paymentstatusCombo.getSelectedItem().toString().equals("Paid")) {
                    try {
                        String sql = "select * from " + u_name + "_payment_status";
                        PreparedStatement st = connection.prepareStatement(sql);
                        ResultSet rs = st.executeQuery();
                        while (rs.next()) {
                            list.add(rs.getString("date"));
                        }
                    } catch (Exception e) {
                    }
                    for (int i = 0; i < list.size(); i++) {
                        if (list.get(i).equals(dateformater.format(date))) {
                            dateAvail = "y";
                        }
                    }

                    if (dateAvail.equals("y")) {

                        try {
                            String sql = "select * from " + u_name + "_payment_status where date='"
                                    + dateformater.format(date) + "' ";
                            PreparedStatement st = connection.prepareStatement(sql);
                            ResultSet rs = st.executeQuery();
                            if (rs.next()) {

                                cashReceive = Integer.parseInt(feeTF.getText()) + rs.getInt("cash_received");

                                try {
                                    String sql_2 = "update " + u_name + "_payment_status set cash_received = '"
                                            + cashReceive + "' where date='" + dateformater.format(date) + "'";
                                    PreparedStatement statement = connection.prepareStatement(sql_2);
                                    statement.executeUpdate();

                                } catch (Exception e) {
                                    e.printStackTrace();
                                }

                            }
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                        dateAvail = "n";

                    } else if (dateAvail.equals("n")) {
                        try {
                            String sql_1 = "insert into " + u_name + "_payment_status"
                                    + "(cash_received,due_received,date)"
                                    + " values(?,?,?)";
                            PreparedStatement statement2 = connection.prepareStatement(sql_1);

                            statement2.setInt(1, Integer.parseInt(feeTF.getText()));
                            statement2.setInt(2, 0);
                            statement2.setString(3, dateformater.format(date));
                            statement2.executeUpdate();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                    }
                }

            } else if (positionTF.getText().equals("No park is available")) {
                JOptionPane.showMessageDialog(null, "There is no space to park!");
            }
            nameTF.setText("");
            userNameTF.setText("");
            phoneTF.setText("");
            emailTF.setText("");
            addressTA.setText("");
            vehicalNoTf.setText("");
            vehicalTypeCombo.setSelectedIndex(0);
            positionTF.setText("");
            feeTF.setText("");
            paymentTypeTF.setText("");
            showMessageLabel.setText("");
            entryTimeTF.setText("");
            paymentstatusCombo.setSelectedIndex(0);

            this.dispose();

        }

    }//GEN-LAST:event_saveBtnMouseClicked

    private void saveBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseEntered
        // TODO add your handling code here:
        setselectcolor(saveBtn, saveFont);
    }//GEN-LAST:event_saveBtnMouseEntered

    private void saveBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBtnMouseExited
        // TODO add your handling code here:
        resetselectcolor(saveBtn, saveFont);
    }//GEN-LAST:event_saveBtnMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEntryFromBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEntryFromBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEntryFromBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEntryFromBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEntryFromBooking().setVisible(true);
            }
        });
    }

    void setselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(255, 250, 250));
        label.setForeground(new Color(31, 58, 147));
    }

    void setclickedcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(31, 58, 147));
        label.setForeground(Color.white);
    }

    void resetselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(Color.WHITE);
        label.setForeground(Color.BLACK);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea addressTA;
    private javax.swing.JPanel btnCancel;
    private javax.swing.JPanel btnSave;
    public javax.swing.JTextField emailTF;
    public javax.swing.JTextField entryTimeTF;
    public javax.swing.JTextField feeTF;
    private javax.swing.JLabel fontCancel;
    private javax.swing.JLabel fontSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nameTF;
    public javax.swing.JTextField paymentTypeTF;
    public javax.swing.JComboBox<String> paymentstatusCombo;
    public javax.swing.JTextField phoneTF;
    public javax.swing.JTextField positionTF;
    private javax.swing.JPanel saveBtn;
    private javax.swing.JLabel saveFont;
    private javax.swing.JLabel showMessageLabel;
    public javax.swing.JLabel titleLabel;
    public javax.swing.JTextField userNameTF;
    public javax.swing.JTextField vehicalNoTf;
    public javax.swing.JComboBox<String> vehicalTypeCombo;
    // End of variables declaration//GEN-END:variables
}
