/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkeasy;

import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Atiq
 */
public class Registration extends javax.swing.JFrame {

    private static Connection connection = null;
    GridBagLayout layout = new GridBagLayout();
    BasicInfoForm basicinfo;
    AddressAndContact addressandcontact;
    OtherInfo otherinfo;
    LogIn login;

    /**
     * Creates new form Registration
     */
    int user_id;
    String firstname, lastname, username, password, confirmpassword, garagename;//basoc information
    String address, city, area, country, email, phone;//address and contacts
    String garagecapacity, workinghour, rate, securityquestion, answer, photo;//Other informations

    public Registration() {
        initComponents();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("parking.png")));

        this.setLocationRelativeTo(this);
        connection = DbConnect.dbconnect();
        basicinfo = new BasicInfoForm();
        addressandcontact = new AddressAndContact();
        otherinfo = new OtherInfo();
        containerFrame.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx = 0;
        c.gridy = 0;
        containerFrame.add(basicinfo, c);
        c.gridx = 0;
        c.gridy = 0;
        containerFrame.add(addressandcontact, c);
        c.gridx = 0;
        c.gridy = 0;
        containerFrame.add(otherinfo, c);
        basicinfo.setVisible(true);
        addressandcontact.setVisible(false);
        otherinfo.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        exitButton = new javax.swing.JLabel();
        miniButton = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        testlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        previousButton1 = new javax.swing.JPanel();
        step1Btn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        step2Btn = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        step3Btn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnFinish = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        containerFrame = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel6.setBackground(new java.awt.Color(45, 62, 80));

        jPanel1.setBackground(new java.awt.Color(249, 148, 6));

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("X");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
        });

        miniButton.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        miniButton.setForeground(new java.awt.Color(255, 255, 255));
        miniButton.setText("-");
        miniButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        miniButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miniButtonMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Registration Form");

        testlabel.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        testlabel.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(91, 91, 91)
                .addComponent(testlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(miniButton)
                .addGap(18, 18, 18)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(miniButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(exitButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(testlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(249, 148, 6));

        previousButton1.setBackground(new java.awt.Color(57, 186, 254));
        previousButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        previousButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                previousButton1MouseClicked(evt);
            }
        });

        step1Btn.setBackground(new java.awt.Color(57, 186, 254));
        step1Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        step1Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                step1BtnMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/right-arrow (1).png"))); // NOI18N
        jLabel1.setText("Step 1");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout step1BtnLayout = new javax.swing.GroupLayout(step1Btn);
        step1Btn.setLayout(step1BtnLayout);
        step1BtnLayout.setHorizontalGroup(
            step1BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, step1BtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        );
        step1BtnLayout.setVerticalGroup(
            step1BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        step2Btn.setBackground(new java.awt.Color(57, 186, 254));
        step2Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        step2Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                step2BtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/right-arrow (1).png"))); // NOI18N
        jLabel2.setText("Step 2");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout step2BtnLayout = new javax.swing.GroupLayout(step2Btn);
        step2Btn.setLayout(step2BtnLayout);
        step2BtnLayout.setHorizontalGroup(
            step2BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step2BtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
        );
        step2BtnLayout.setVerticalGroup(
            step2BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step2BtnLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        step3Btn.setBackground(new java.awt.Color(57, 186, 254));
        step3Btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        step3Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                step3BtnMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/right-arrow (1).png"))); // NOI18N
        jLabel6.setText("Step 3");
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout step3BtnLayout = new javax.swing.GroupLayout(step3Btn);
        step3Btn.setLayout(step3BtnLayout);
        step3BtnLayout.setHorizontalGroup(
            step3BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step3BtnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        step3BtnLayout.setVerticalGroup(
            step3BtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(step3BtnLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnFinish.setBackground(new java.awt.Color(57, 186, 254));
        btnFinish.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFinish.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFinishMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Finish");

        javax.swing.GroupLayout btnFinishLayout = new javax.swing.GroupLayout(btnFinish);
        btnFinish.setLayout(btnFinishLayout);
        btnFinishLayout.setHorizontalGroup(
            btnFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnFinishLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnFinishLayout.setVerticalGroup(
            btnFinishLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnCancel.setBackground(new java.awt.Color(57, 186, 254));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Cancel");

        javax.swing.GroupLayout btnCancelLayout = new javax.swing.GroupLayout(btnCancel);
        btnCancel.setLayout(btnCancelLayout);
        btnCancelLayout.setHorizontalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
        );
        btnCancelLayout.setVerticalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout previousButton1Layout = new javax.swing.GroupLayout(previousButton1);
        previousButton1.setLayout(previousButton1Layout);
        previousButton1Layout.setHorizontalGroup(
            previousButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(previousButton1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(step2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(step3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        previousButton1Layout.setVerticalGroup(
            previousButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(step1Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(previousButton1Layout.createSequentialGroup()
                .addGroup(previousButton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(step3Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(step2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previousButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(previousButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/parking (8).png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Vijaya", 3, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("ParkEasy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        containerFrame.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout containerFrameLayout = new javax.swing.GroupLayout(containerFrame);
        containerFrame.setLayout(containerFrameLayout);
        containerFrameLayout.setHorizontalGroup(
            containerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        containerFrameLayout.setVerticalGroup(
            containerFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(containerFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(containerFrame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitButtonMouseClicked

    private void miniButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miniButtonMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_miniButtonMouseClicked

    private void previousButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_previousButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_previousButton1MouseClicked

    private void step1BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_step1BtnMouseClicked
        // TODO add your handling code here:
        basicinfo.setVisible(true);
        addressandcontact.setVisible(false);
        otherinfo.setVisible(false);
        setcolor(step1Btn);
        resetcolor(step2Btn);
        resetcolor(step3Btn);
        resetcolor(btnCancel);
        resetcolor(btnFinish);
    }//GEN-LAST:event_step1BtnMouseClicked

    private void step2BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_step2BtnMouseClicked
         
        
        
        firstname = basicinfo.firstname();
        lastname = basicinfo.lastname();
        username = basicinfo.username();
        password = basicinfo.password();
        confirmpassword = basicinfo.confirmpassword();
        garagename = basicinfo.garagename();
        if (firstname.isEmpty() || lastname.isEmpty() || username.isEmpty() || password.isEmpty()
                || confirmpassword.isEmpty() || garagename.isEmpty()) {
            testlabel.setText("Some fields are required!");
            basicinfo.setVisible(false);
            addressandcontact.setVisible(true);
            otherinfo.setVisible(false);
        } else if (!password.equals(confirmpassword)) {
            testlabel.setText("password does not matched!");
            basicinfo.setVisible(false);
            addressandcontact.setVisible(true);
            otherinfo.setVisible(false);

        } else {

            try {

                String sql = "select * from users where user_name='" + username + "'";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();

                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "user name is exist!");
                    //userNameTF.requestFocus();
                    st.close();
                    rs.close();
                } else {

                    testlabel.setText("");
                    basicinfo.setVisible(false);
                    addressandcontact.setVisible(true);
                    otherinfo.setVisible(false);
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }

        setcolor(step2Btn);
        resetcolor(step1Btn);
        resetcolor(step3Btn);
        resetcolor(btnCancel);
        resetcolor(btnFinish);


    }//GEN-LAST:event_step2BtnMouseClicked

    private void step3BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_step3BtnMouseClicked
        // TODO add your handling code here:
        testlabel.setText("");
        address = addressandcontact.address();
        city = addressandcontact.city();
        area = addressandcontact.area();
        country = addressandcontact.country();
        email = addressandcontact.email();
        phone = addressandcontact.phone();

        if (address.isEmpty() || city.isEmpty() || area.isEmpty() || country.equals("Select Country")
                || email.isEmpty() || phone.isEmpty()) {
            testlabel.setText("Some fields are required!");
            basicinfo.setVisible(false);
            addressandcontact.setVisible(false);
            otherinfo.setVisible(true);

        } else {
            testlabel.setText("");
            basicinfo.setVisible(false);
            addressandcontact.setVisible(false);
            otherinfo.setVisible(true);

        }
        setcolor(step3Btn);
        resetcolor(step2Btn);
        resetcolor(step1Btn);
        resetcolor(btnCancel);
        resetcolor(btnFinish);
    }//GEN-LAST:event_step3BtnMouseClicked

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        login = new LogIn();
        resetcolor(step1Btn);
        resetcolor(step2Btn);
        resetcolor(step3Btn);
        setcolor(btnCancel);
        resetcolor(btnFinish);
        login.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnFinishMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinishMouseClicked
        // TODO add your handling code here:

        garagecapacity = otherinfo.garagecapacity();
        workinghour = otherinfo.workinghour();
        rate = otherinfo.rate();
        securityquestion = otherinfo.securiquestion();
        answer = otherinfo.answer();

        if (address.isEmpty() || city.isEmpty() || area.isEmpty() || country.equals("Select Country")
                || email.isEmpty() || phone.isEmpty()||firstname.isEmpty() || lastname.isEmpty() || username.isEmpty() || password.isEmpty()
                || confirmpassword.isEmpty() || garagename.isEmpty()||garagecapacity.isEmpty() || workinghour.isEmpty() || rate.isEmpty() || securityquestion.equals("Select one question")
                || answer.isEmpty()) {
            testlabel.setText("Some fields are required!");
            basicinfo.setVisible(false);
            addressandcontact.setVisible(false);
            otherinfo.setVisible(true);

        } else {

            try {

                String sql_1 = "insert into users"
                        + "(user_name,user_type,password,security_question,answer)"
                        + " values(?,?,?,?,?)";
                PreparedStatement statement2 = connection.prepareStatement(sql_1);
                statement2.setString(1, username);
                statement2.setString(2, "park_owner");
                statement2.setString(3, password);
                statement2.setString(4, securityquestion);
                statement2.setString(5, answer);

                statement2.executeUpdate();
                statement2.close();

                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            try {
                String sql_3 = "select * from users where user_name='" + username + "'";
                PreparedStatement st1 = connection.prepareStatement(sql_3);
                ResultSet rs1 = st1.executeQuery();

                if (rs1.next()) {

                    user_id = rs1.getInt("id");
                    st1.close();
                    rs1.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            try {
                String sql_1 = "insert into park_owner"
                        + "(first_name,last_name,park_name,address,city,region,country,email,phone,capacity,working_hour,rate,user_id,user_name)"
                        + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                PreparedStatement statement = connection.prepareStatement(sql_1);

                statement.setString(1, firstname);
                statement.setString(2, lastname);
                statement.setString(3, garagename);
                statement.setString(4, address);
                statement.setString(5, city);
                statement.setString(6, area);
                statement.setString(7, country);
                statement.setString(8, email);
                statement.setString(9, phone);
                statement.setString(10, garagecapacity);
                statement.setString(11, workinghour);
                statement.setString(12, rate);
                statement.setInt(13, user_id);
                statement.setString(14, username);
                statement.executeUpdate();

                System.out.println("Insrt sucessfull");
                JOptionPane.showMessageDialog(null, "Registration sucessfull");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            try {
                String sql_1 = "CREATE TABLE IF NOT EXISTS " + username + "_sensor_status (\n"
                        + "	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,\n"
                        + "	p1 INT NOT NULL,\n"
                        + "	p2 INT NOT NULL,\n"
                        + "	p3 INT NOT NULL,\n"
                        + "	p4 INT NOT NULL,\n"
                        + "	p5 INT NOT NULL,\n"
                        + "	p6 INT NOT NULL,\n"
                        + "	p7 INT NOT NULL,\n"
                        + "	p8 INT NOT NULL,\n"
                        + "	p9 INT NOT NULL,\n"
                        + "	p10 INT NOT NULL,\n"
                        + "	p11 INT NOT NULL,\n"
                        + "	p12 INT NOT NULL,\n"
                        + "	p13 INT NOT NULL,\n"
                        + "	p14 INT NOT NULL,\n"
                         + "	available INT NULL,\n"
                        + "	date text NOT NULL\n"
                        + ");";
                PreparedStatement st = connection.prepareStatement(sql_1);
                st.execute(sql_1);

            } catch (Exception e) {
            }

            try {
                String sql_2 = "insert into " + username + "_sensor_status "
                        + "(p1,p2,p3,p4,p5,p6,p7,p8,p9,p10,p11,p12,p13,p14,date)"
                        + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                PreparedStatement statement = connection.prepareStatement(sql_2);

                statement.setInt(1, 0);
                statement.setInt(2, 0);
                statement.setInt(3, 0);
                statement.setInt(4, 0);
                statement.setInt(5, 0);
                statement.setInt(6, 0);
                statement.setInt(7, 0);
                statement.setInt(8, 0);
                statement.setInt(9, 0);
                statement.setInt(10, 0);
                statement.setInt(11, 0);
                statement.setInt(12, 0);
                statement.setInt(13, 0);
                statement.setInt(14, 0);
                statement.setString(15, "12/05/2018");

                statement.executeUpdate();

                System.out.println("Insrt sucessfull");
                //JOptionPane.showMessageDialog(null, "Registration sucessfull");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            
             try {
                String sql_1 = "CREATE TABLE IF NOT EXISTS " + username + "_payment_status (\n"
                        + "	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,\n"
                        + "	cash_received INT  NULL,\n"
                        + "	due_received INT  NULL,\n"
                        + "	date text NOT NULL\n"
                        + ");";
                PreparedStatement st = connection.prepareStatement(sql_1);
                st.execute(sql_1);

            } catch (Exception e) {
            }

            try {
                String sql_2 = "insert into " + username + "_payment_status "
                        + "(cash_received,due_received,date)"
                        + " values(?,?,?)";

                PreparedStatement statement2 = connection.prepareStatement(sql_2);

                statement2.setInt(1, 0);
                statement2.setInt(2, 0);
                statement2.setString(3, "12/12/1990");
                statement2.executeUpdate();

                System.out.println("Insrt sucessfull");
                //JOptionPane.showMessageDialog(null, "Registration sucessfull");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
            
            
            try {
                String sql_1 = "CREATE TABLE IF NOT EXISTS " + username + "_parked_status (\n"
                        + "	id INT PRIMARY KEY AUTO_INCREMENT NOT NULL ,\n"
                        + "	name text NOT NULL,\n"
                        + "	user_name text NOT NULL,\n"
                        + "	phone text NOT NULL,\n"
                        + "	email text NOT NULL,\n"
                        + "	address text NOT NULL,\n"
                        + "	vehical_type text NOT NULL,\n"
                        + "	vehical_no text NOT NULL,\n"
                        + "	position text NOT NULL,\n"
                        + "	fee INT NOT NULL,\n"
                        + "	paid INT  NULL,\n"
                        + "	due INT  NULL,\n"
                        + "	extra_fee INT NULL,\n"
                        + "	payment text NOT NULL,\n"
                        + "	payment_status text NOT NULL,\n"
                        + "	date text NOT NULL,\n"
                        + "	time text NOT NULL,\n"
                         + "	entry_time text NULL,\n"
                         + "	exit_time text NULL,\n"
                        + "	status INT NULL\n"
                        + ");";
                PreparedStatement st = connection.prepareStatement(sql_1);
                st.execute(sql_1);

            } catch (Exception e) {
            }

            try {
                String sql_2 = "insert into " + username + "_parked_status "
                        + "(name,user_name,phone,email,address,vehical_type,vehical_no,"
                        + "position,fee,paid,due,extra_fee,payment,payment_status,"
                        + "date,time,entry_time,exit_time,status)"
                        + " values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

                PreparedStatement statement2 = connection.prepareStatement(sql_2);

                statement2.setString(1, "--");
                statement2.setString(2, "--");
                statement2.setString(3, "--");
                statement2.setString(4, "--");
                statement2.setString(5, "--");
                statement2.setString(6, "--");
                statement2.setString(7, "--");
                statement2.setString(8, "--");
                statement2.setInt(9, 0);
                statement2.setInt(10, 0);
                statement2.setInt(11, 0);
                statement2.setInt(12, 0);
                statement2.setString(13, "--");
                statement2.setString(14, "--");
                statement2.setString(15, "--");
                statement2.setString(16, "--");
                statement2.setString(17, "--");
                statement2.setString(18, "--");
                statement2.setInt(19, 0);

                statement2.executeUpdate();

                System.out.println("Insrt sucessfull");
                //JOptionPane.showMessageDialog(null, "Registration sucessfull");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            login = new LogIn();
            login.setVisible(true);
            this.setVisible(false);
        }

        resetcolor(step1Btn);
        resetcolor(step2Btn);
        resetcolor(step3Btn);
        resetcolor(btnCancel);
        setcolor(btnFinish);

    }//GEN-LAST:event_btnFinishMouseClicked

    void setcolor(JPanel panel) {
        panel.setBackground(new Color(153, 204, 255));
    }

    void resetcolor(JPanel panel) {
        panel.setBackground(new Color(57, 186, 254));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancel;
    private javax.swing.JPanel btnFinish;
    private javax.swing.JPanel containerFrame;
    private javax.swing.JLabel exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel miniButton;
    private javax.swing.JPanel previousButton1;
    private javax.swing.JPanel step1Btn;
    private javax.swing.JPanel step2Btn;
    private javax.swing.JPanel step3Btn;
    private javax.swing.JLabel testlabel;
    // End of variables declaration//GEN-END:variables
}
