/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkeasy;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Atiq
 */
public class ReleseForm extends javax.swing.JFrame {

    /**
     * Creates new form ReleseForm
     */
    ArrayList<String> list = new ArrayList();
    Home home;
    int u_id, fee, extra, due, paid, topay;
    String u_name;
    private static Connection connection = null;
    String parkedTableName;

    //Home home;
    public ReleseForm() {
        initComponents();
        this.setResizable(false);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("parking.png")));
        //  home=new Home(u_id,u_name);
        this.setLocationRelativeTo(this);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        connection = DbConnect.dbconnect();
        //home=new Home(u_id, u_name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        phoneTF = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        emailTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressTF = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        vehicalNoTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        vehicalTypeTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        positionTF = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        entryTimeTF = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        exitTimeTF = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        feeTF = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        extraFeeTF = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        totalTF = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        paidTF = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        dueTF = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        btnRelese = new javax.swing.JPanel();
        fontSave = new javax.swing.JLabel();
        btnCancel = new javax.swing.JPanel();
        fontCancel = new javax.swing.JLabel();
        toPayTF = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        paymentStatusTF = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 148, 6));

        titleLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Demo Station");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 102, 0), 2, true), "Vehical Release Form", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 204))); // NOI18N

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Vijaya", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ParkEasy");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/parking (10).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel2))
        );

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(45, 62, 80));
        jLabel13.setText("Name:");

        nameTF.setBackground(new java.awt.Color(109, 122, 138));
        nameTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        nameTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(45, 62, 80));
        jLabel22.setText("Phone No:");

        phoneTF.setBackground(new java.awt.Color(109, 122, 138));
        phoneTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(45, 62, 80));
        jLabel21.setText("Email:");

        emailTF.setBackground(new java.awt.Color(109, 122, 138));
        emailTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        emailTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(45, 62, 80));
        jLabel15.setText("Address:");

        addressTF.setBackground(new java.awt.Color(109, 122, 138));
        addressTF.setColumns(20);
        addressTF.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        addressTF.setForeground(new java.awt.Color(255, 255, 255));
        addressTF.setLineWrap(true);
        addressTF.setRows(5);
        jScrollPane1.setViewportView(addressTF);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(45, 62, 80));
        jLabel14.setText("Vehical No:");

        vehicalNoTF.setBackground(new java.awt.Color(109, 122, 138));
        vehicalNoTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehicalNoTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(45, 62, 80));
        jLabel16.setText("Vehical Type:");

        vehicalTypeTF.setBackground(new java.awt.Color(109, 122, 138));
        vehicalTypeTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        vehicalTypeTF.setForeground(new java.awt.Color(255, 255, 255));
        vehicalTypeTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicalTypeTFActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(45, 62, 80));
        jLabel17.setText("Position:");

        positionTF.setBackground(new java.awt.Color(109, 122, 138));
        positionTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        positionTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(45, 62, 80));
        jLabel18.setText("Entry Time:");

        entryTimeTF.setBackground(new java.awt.Color(109, 122, 138));
        entryTimeTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        entryTimeTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(45, 62, 80));
        jLabel20.setText("Exit Time:");

        exitTimeTF.setBackground(new java.awt.Color(109, 122, 138));
        exitTimeTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        exitTimeTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(45, 62, 80));
        jLabel19.setText("Fee:");

        feeTF.setBackground(new java.awt.Color(109, 122, 138));
        feeTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        feeTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(45, 62, 80));
        jLabel23.setText("Extra:");

        extraFeeTF.setBackground(new java.awt.Color(109, 122, 138));
        extraFeeTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        extraFeeTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(45, 62, 80));
        jLabel24.setText("Total:");

        totalTF.setBackground(new java.awt.Color(109, 122, 138));
        totalTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        totalTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(45, 62, 80));
        jLabel25.setText("Pay now:");

        paidTF.setBackground(new java.awt.Color(109, 122, 138));
        paidTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paidTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(45, 62, 80));
        jLabel26.setText("Paid:");

        dueTF.setBackground(new java.awt.Color(109, 122, 138));
        dueTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dueTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(45, 62, 80));
        jLabel27.setText("Due:");

        btnRelese.setBackground(new java.awt.Color(255, 255, 255));
        btnRelese.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRelese.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRelese.setPreferredSize(new java.awt.Dimension(150, 24));
        btnRelese.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnReleseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReleseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReleseMouseExited(evt);
            }
        });

        fontSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Remove_Property_20px_1.png"))); // NOI18N
        fontSave.setText("Confirm Relese");
        fontSave.setIconTextGap(8);

        javax.swing.GroupLayout btnReleseLayout = new javax.swing.GroupLayout(btnRelese);
        btnRelese.setLayout(btnReleseLayout);
        btnReleseLayout.setHorizontalGroup(
            btnReleseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnReleseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnReleseLayout.setVerticalGroup(
            btnReleseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontSave, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setPreferredSize(new java.awt.Dimension(150, 24));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });

        fontCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Redo_20px.png"))); // NOI18N
        fontCancel.setText("Cancel");
        fontCancel.setIconTextGap(8);

        javax.swing.GroupLayout btnCancelLayout = new javax.swing.GroupLayout(btnCancel);
        btnCancel.setLayout(btnCancelLayout);
        btnCancelLayout.setHorizontalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCancelLayout.setVerticalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontCancel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        toPayTF.setBackground(new java.awt.Color(109, 122, 138));
        toPayTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        toPayTF.setForeground(new java.awt.Color(255, 255, 255));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(45, 62, 80));
        jLabel28.setText("Payment status: ");

        paymentStatusTF.setBackground(new java.awt.Color(109, 122, 138));
        paymentStatusTF.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        paymentStatusTF.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel24)
                            .addComponent(jLabel23)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel16)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel13))
                        .addGap(42, 42, 42)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(phoneTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(emailTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vehicalNoTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vehicalTypeTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(positionTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(entryTimeTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitTimeTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(feeTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(extraFeeTF, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dueTF)
                            .addComponent(paidTF)
                            .addComponent(totalTF)
                            .addComponent(toPayTF)
                            .addComponent(nameTF)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnRelese, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addGap(16, 16, 16)
                                .addComponent(paymentStatusTF)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel13)
                            .addComponent(nameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(phoneTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehicalNoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(vehicalTypeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(positionTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(entryTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(exitTimeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(feeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(extraFeeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(totalTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(paidTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(dueTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(toPayTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentStatusTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(btnRelese, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jPanel3.setBackground(new java.awt.Color(249, 148, 6));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehicalTypeTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicalTypeTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehicalTypeTFActionPerformed

    private void btnReleseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReleseMouseClicked
        // TODO add your handling code here:
        SimpleDateFormat dateformater = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        topay = Integer.parseInt(toPayTF.getText());

        int total = paid + topay;
        int dueReceive;
        String dateAvail = "n";
        setclickedcolor(btnRelese, fontSave);
        if ((fee + extra) != total) {
            JOptionPane.showMessageDialog(null, "Please complete payment to relese car.");
        } else {

            try {
                String sql = "update " + parkedTableName + " set status = '" + 0 + "' "
                        + ",paid='" + total + "',due='" + 0 + "'"
                        + ",exit_time='" + exitTimeTF.getText() + "'"
                        + " where vehical_no='" + vehicalNoTF.getText() + "' AND status='" + 1 + "'";
                PreparedStatement statement = connection.prepareStatement(sql);
                statement.executeUpdate();
                statement.close();
                //JOptionPane.showMessageDialog(null, "Car relese successful.");

                
            } catch (HeadlessException | SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
            
            
            try {
                String sql = "update book_notification set approval_status ='released',status='0',sensor_status='0' "
                            + " where vehicle_no='" + vehicalNoTF.getText() + "' AND approval_status='parked'";
                    PreparedStatement statement = connection.prepareStatement(sql);
                    statement.executeUpdate();

                    statement.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
            
            
            if(Integer.parseInt(dueTF.getText())>0)
            {
            try {
                String sql = "select * from " + u_name + "_payment_status";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                while (rs.next()) {
                    list.add(rs.getString("date"));
                }
            } catch (Exception e) {
            }
            for (int i = 0; i < list.size(); i++) {
                if (list.get(i).equals(dateformater.format(date))) {
                    dateAvail = "y";
                }
            }

            if (dateAvail.equals("y")) {
                try {
                    String sql = "select * from " + u_name + "_payment_status where date='" + dateformater.format(date) + "' ";
                    PreparedStatement st = connection.prepareStatement(sql);
                    ResultSet rs = st.executeQuery();
                    if (rs.next()) {

                        dueReceive = Integer.parseInt(toPayTF.getText()) + rs.getInt("due_received");

                        try {
                            String sql_2 = "update " + u_name + "_payment_status set due_received = '" + dueReceive + "' where date='" + dateformater.format(date) + "'";
                            PreparedStatement statement = connection.prepareStatement(sql_2);
                            statement.executeUpdate();

                        } catch (Exception e) {
                        }

                    }
                } catch (Exception e) {
                }
                dateAvail = "n";
            } else if (dateAvail.equals("n")) {
                try {
                    String sql_1 = "insert into " + u_name + "_payment_status"
                            + "(cash_received,due_received,date)"
                            + " values(?,?,?)";
                    PreparedStatement statement2 = connection.prepareStatement(sql_1);

                    statement2.setInt(1, 0);
                    statement2.setInt(2, Integer.parseInt(toPayTF.getText()));
                    statement2.setString(3, dateformater.format(date));
                    statement2.executeUpdate();
                } catch (Exception e) {
                }

            }

        }
            this.dispose();
        }


    }//GEN-LAST:event_btnReleseMouseClicked

    private void btnReleseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReleseMouseEntered

        // TODO add your handling code here:
        setselectcolor(btnRelese, fontSave);
    }//GEN-LAST:event_btnReleseMouseEntered

    private void btnReleseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReleseMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnRelese, fontSave);
    }//GEN-LAST:event_btnReleseMouseExited

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        setclickedcolor(btnCancel, fontCancel);
        this.dispose();

    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        // TODO add your handling code here:
        setselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReleseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReleseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReleseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReleseForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReleseForm().setVisible(true);
            }
        });
    }

    void setselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(255, 250, 250));
        label.setForeground(new Color(31, 58, 147));
    }

    void setclickedcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(31, 58, 147));
        label.setForeground(Color.white);
    }

    void resetselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(Color.WHITE);
        label.setForeground(Color.BLACK);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextArea addressTF;
    private javax.swing.JPanel btnCancel;
    private javax.swing.JPanel btnRelese;
    public javax.swing.JLabel dateLabel;
    public javax.swing.JTextField dueTF;
    public javax.swing.JTextField emailTF;
    public javax.swing.JTextField entryTimeTF;
    public javax.swing.JTextField exitTimeTF;
    public javax.swing.JTextField extraFeeTF;
    public javax.swing.JTextField feeTF;
    private javax.swing.JLabel fontCancel;
    private javax.swing.JLabel fontSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextField nameTF;
    public javax.swing.JTextField paidTF;
    public javax.swing.JTextField paymentStatusTF;
    public javax.swing.JTextField phoneTF;
    public javax.swing.JTextField positionTF;
    public javax.swing.JLabel titleLabel;
    public javax.swing.JTextField toPayTF;
    public javax.swing.JTextField totalTF;
    public javax.swing.JTextField vehicalNoTF;
    public javax.swing.JTextField vehicalTypeTF;
    // End of variables declaration//GEN-END:variables
}
