/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package parkeasy;

import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Atiq
 */
public class Requests extends javax.swing.JPanel {

    /**
     * Creates new form Tutorial
     */
    private static Connection connection = null;
    int user_id;
    String park_name="";
    String user_name;
    String message;
    public Requests() {
        initComponents();
               
    }
    
     public Requests(int u_id,String u_name) {
        initComponents();
        user_id=u_id;
        user_name=u_name;
        connection = DbConnect.dbconnect();
        showDetailTextArea.setText("");
        parkName();
        //showBookingNotification();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnSave = new javax.swing.JPanel();
        fontSave = new javax.swing.JLabel();
        btnCancel = new javax.swing.JPanel();
        fontCancel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showDetailTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(710, 470));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.setPreferredSize(new java.awt.Dimension(150, 24));
        btnSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSaveMouseExited(evt);
            }
        });

        fontSave.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Remove_Property_20px.png"))); // NOI18N
        fontSave.setText("Relese");
        fontSave.setIconTextGap(8);

        javax.swing.GroupLayout btnSaveLayout = new javax.swing.GroupLayout(btnSave);
        btnSave.setLayout(btnSaveLayout);
        btnSaveLayout.setHorizontalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSaveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontSave, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnSaveLayout.setVerticalGroup(
            btnSaveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontSave, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        btnCancel.setBackground(new java.awt.Color(255, 255, 255));
        btnCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.setPreferredSize(new java.awt.Dimension(150, 24));
        btnCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelMouseExited(evt);
            }
        });

        fontCancel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fontCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/parkeasy/icons/icons8_Erase_20px.png"))); // NOI18N
        fontCancel.setText("Clear");
        fontCancel.setIconTextGap(8);

        javax.swing.GroupLayout btnCancelLayout = new javax.swing.GroupLayout(btnCancel);
        btnCancel.setLayout(btnCancelLayout);
        btnCancelLayout.setHorizontalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnCancelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fontCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        btnCancelLayout.setVerticalGroup(
            btnCancelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(fontCancel, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        showDetailTextArea.setColumns(20);
        showDetailTextArea.setLineWrap(true);
        showDetailTextArea.setRows(5);
        showDetailTextArea.setTabSize(10);
        showDetailTextArea.setText("Notification details wii be shown here...");
        showDetailTextArea.setWrapStyleWord(true);
        jScrollPane1.setViewportView(showDetailTextArea);

        requestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        requestTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(requestTable);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 0));
        jLabel1.setText("Request Notifications");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseClicked
        // TODO add your handling code here:
        setclickedcolor(btnSave, fontSave);
        SimpleDateFormat time = new SimpleDateFormat("HH:mm dd/MM/yyyy");
        SimpleDateFormat dateformate = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String exit_time = time.format(date);
        String dateLabel = dateformate.format(date);
        setclickedcolor(btnCancel, fontCancel);
        ReleseFromRequest releseForm = new ReleseFromRequest();

        int row = requestTable.getSelectedRow();

        if (row >= 0) {
            String tableClicked = (requestTable.getModel().getValueAt(row, 0).toString());
            String tableClicked2 = (requestTable.getModel().getValueAt(row, 1).toString());

            try {
                String sql = "select * from park_owner where user_id='" + user_id + "' ";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    releseForm.titleLabel.setText(rs.getString("park_name"));
                }
            } catch (Exception e) {

            }
            
            
            try {
                 String sql = "select * from request_to_urgent_park where user_name='"
                        +""+ tableClicked2 + "' AND (reply_request_to_park='pending' OR reply_request_to_park='managed')"
                        + "AND date='"+dateformate.format(date)+"'AND park_name='"+park_name+"'";
                        
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                                       releseForm.cus_username=rs.getString("user_name");
                   releseForm.cus_vehicle_no=rs.getString("vehicle_no");
                   releseForm.cus_vehicle_type=rs.getString("vehicle_type");
                }
            } catch (Exception e) {
            }
            

            try {
                String sql = "select * from "+user_name+"_parked_status where user_name='"
                        + tableClicked + "' AND status='" + 1 + "'";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();

                if (rs.next()) {

                    releseForm.nameTF.setText(rs.getString("name"));
                    releseForm.phoneTF.setText(rs.getString("phone"));
                    releseForm.emailTF.setText(rs.getString("email"));
                    releseForm.addressTF.setText(rs.getString("address"));
                    releseForm.vehicalNoTF.setText(rs.getString("vehical_no"));
                    releseForm.vehicalTypeTF.setText(rs.getString("vehical_type"));
                    releseForm.positionTF.setText(rs.getString("position"));
                    releseForm.entryTimeTF.setText(rs.getString("entry_time"));
                    releseForm.exitTimeTF.setText(exit_time);
                    releseForm.feeTF.setText(String.valueOf(rs.getInt("fee")));
                    releseForm.extraFeeTF.setText(String.valueOf(rs.getInt("extra_fee")));

                    releseForm.paidTF.setText(String.valueOf(rs.getInt("paid")));
                    releseForm.dueTF.setText(String.valueOf(rs.getInt("due")));
                    releseForm.paymentStatusTF.setText("Paid");
                    releseForm.dateLabel.setText("Current Date:" + dateLabel);
                    releseForm.toPayTF.setText("0");
                    releseForm.parkedTableName = user_name+"_parked_status";

                    int rs_paid = rs.getInt("paid"), rs_due = rs.getInt("due"), rs_fee = rs.getInt("fee"), rs_extra = rs.getInt("extra_fee");

                    releseForm.due = rs_due;
                    releseForm.paid = rs_paid;
                    releseForm.extra = rs_extra;
                    releseForm.fee = rs_fee;
                    int total = rs_extra + rs_fee;
                    releseForm.totalTF.setText(String.valueOf(total));
                    releseForm.u_id = user_id;
                    releseForm.u_name = user_name;
                    releseForm.toPayTF.requestFocus();
                    
                    
                    
                    

                    releseForm.setVisible(true);
                }

            } catch (SQLException ex) {
                Logger.getLogger(MainFraim.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a row to release car.");
        }
        
    }//GEN-LAST:event_btnSaveMouseClicked

    private void btnSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseEntered

        // TODO add your handling code here:
        setselectcolor(btnSave, fontSave);
    }//GEN-LAST:event_btnSaveMouseEntered

    private void btnSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSaveMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnSave, fontSave);
    }//GEN-LAST:event_btnSaveMouseExited

    private void btnCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseClicked
        // TODO add your handling code here:
        setclickedcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseClicked

    private void btnCancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseEntered
        // TODO add your handling code here:
        setselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseEntered

    private void btnCancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelMouseExited
        // TODO add your handling code here:
        resetselectcolor(btnCancel, fontCancel);
    }//GEN-LAST:event_btnCancelMouseExited

    private void requestTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestTableMouseClicked

        String time="";
        String message="";
        SimpleDateFormat df=new SimpleDateFormat("dd/MM/yyyy");
        Date date= new Date();
       
        
        int row = requestTable.getSelectedRow();
        if (row >= 0) {
            String tableClicked = (requestTable.getModel().getValueAt(row, 0).toString());
             String tableClicked2 = (requestTable.getModel().getValueAt(row, 1).toString());
            
             
             try {
                String sql_1 = "select time from response_to_urgent_park"
                        + " where activity='allow' AND park_name='" + park_name + "'AND response_from='"+tableClicked+"'";

                PreparedStatement st = connection.prepareStatement(sql_1);
                ResultSet rs_1 = st.executeQuery();
                if (rs_1.next()) {
                    time=rs_1.getString("time");
                }
            } catch (Exception e) {
            }
             
            
            try {
                String sql = "select * from "+user_name+"_parked_status where user_name='"
                        +""+ tableClicked + "' AND status='" + 1 + "'";
                        
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                    //time=rs.getString("time");
                    message=rs.getString("name")
                            +"\tVehicle No: "+rs.getString("vehical_no")
                            +"\tVehicle Type: "+rs.getString("vehical_type")
                            +"\tBooking Time: "+rs.getString("time")
                            +"\tBooking Date: "+rs.getString("date")
                            +"\twants to relese car for request from ";
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
                        try {
                String sql = "select * from request_to_urgent_park where user_name='"
                        +""+ tableClicked2 + "' AND (reply_request_to_park='pending' OR reply_request_to_park='managed')"
                        + "AND date='"+df.format(date)+"'AND park_name='"+park_name+"'";
                        
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                if(rs.next()){
                   // time=rs.getString("time");

                    message=message+rs.getString("user_name")
                            +"\tVehicle No: "+rs.getString("vehicle_no")
                            +"\tVehicle Type: "+rs.getString("vehicle_type")
                            +"\twhich is valid for ";
                }

            } catch (Exception e) {
                e.printStackTrace();
            }
            
            //showDetailTextArea.setText(message);
            
            double bookedTime=0;

        SimpleDateFormat daeformatFormat = new SimpleDateFormat("HH:mm:ss");
        //Date date = new Date();
        String currentTime = daeformatFormat.format(date);
        String hour = String.valueOf(currentTime.charAt(0)) + String.valueOf(currentTime.charAt(1));
        String min = String.valueOf(currentTime.charAt(3)) + String.valueOf(currentTime.charAt(4));
        String sec = String.valueOf(currentTime.charAt(6)) + String.valueOf(currentTime.charAt(7));
        double currentTimeinSec = Long.parseLong(hour) * 60 * 60 + (Long.parseLong(min) * 60) + (Long.parseLong(sec));

        String hour2 = String.valueOf(time.charAt(0)) + String.valueOf(time.charAt(1));
            String min2 = String.valueOf(time.charAt(3)) + String.valueOf(time.charAt(4));
            String sec2 = String.valueOf(time.charAt(6)) + String.valueOf(time.charAt(7));
             bookedTime = Long.parseLong(hour2) * 60 * 60 + (Long.parseLong(min2) * 60) + (Long.parseLong(sec2));
            float remainingTime = (float) ((bookedTime+660-currentTimeinSec) / 60);    
            message=message+String.format("%.2f", remainingTime)+" Minutes";
            
            showDetailTextArea.setText(message);
            
           /* try {
                  String sql = "update book_notification set notification_type ='' "
                            + " where notification_type='New'AND vehicle_no='"+tableClicked+"'AND park_name="
                          + "'"+park_name+"' ";
                    PreparedStatement statement = connection.prepareStatement(sql);
                    statement.executeUpdate();

                    statement.close();
            } catch (Exception e) {
                e.printStackTrace();
            }*/

        }
        
        
        
    }//GEN-LAST:event_requestTableMouseClicked

    
        public void showRequestNotification(){
         SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        Date date = new Date();
        String currentDate = dateFormat.format(date);
        
        try {
             String sql_1 = "select response_from,response_for,date,activity "
                    + "from response_to_urgent_park"
                           + " where date='" + currentDate + "'AND park_name='" + park_name + "'AND "
                    + "(activity= 'allow')";
             
            PreparedStatement st = connection.prepareStatement(sql_1);
            ResultSet rs_1 = st.executeQuery();
            requestTable.setModel(DbUtils.resultSetToTableModel(rs_1));
            //bookedTable.setSelectionBackground(Color.red);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
  
        public  void parkName(){
        try {
                String sql = "select * from park_owner where user_id='" + user_id + "' ";
                PreparedStatement st = connection.prepareStatement(sql);
                ResultSet rs = st.executeQuery();
                if (rs.next()) {
                    park_name=rs.getString("park_name");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }      
    }
    
    
        void setselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(255, 250, 250));
        label.setForeground(new Color(31, 58, 147));
    }

    void setclickedcolor(JPanel panel, JLabel label) {
        panel.setBackground(new Color(31, 58, 147));
        label.setForeground(Color.white);
    }

    void resetselectcolor(JPanel panel, JLabel label) {
        panel.setBackground(Color.WHITE);
        label.setForeground(Color.BLACK);
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCancel;
    private javax.swing.JPanel btnSave;
    private javax.swing.JLabel fontCancel;
    private javax.swing.JLabel fontSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable requestTable;
    public javax.swing.JTextArea showDetailTextArea;
    // End of variables declaration//GEN-END:variables
}
